### ISSUE TITLE
typo at docs site

### ISSUE THREAD

**Issue by lachnerd** [ricsanfre/pi-cluster#108]
Hi,

thx for that great project docs.

At https://picluster.ricsanfre.com/docs/k3s-installation/ i found a typo at "https://picluster.ricsanfre.com/docs/k3s-installation/"

there is:
"curl -sfL https://get.k3s.io | K3S_URL='https://<k3s_master_ip>:6443' K3S_TOKEN=<server_token> sh -s - --node-label 'node_type=worker --kubelet-arg 'config=/etc/rancher/k3s/kubelet.config' --kube-proxy-arg 'metrics-bind-address=0.0.0.0''"

should be
"curl -sfL https://get.k3s.io | K3S_URL='https://<k3s_master_ip>:6443' K3S_TOKEN=<server_token> sh -s - --node-label 'node_type=worker' --kubelet-arg 'config=/etc/rancher/k3s/kubelet.config' --kube-proxy-arg 'metrics-bind-address=0.0.0.0'"

**Comment by ricsanfre** [comment]
Thanks @lachnerd
