### ISSUE TITLE
Kafka cluster not starting with ArgoCD

### ISSUE THREAD

**Issue by ricsanfre** [ricsanfre/pi-cluster#216]
When deploying Kafka using Strimzi-operator with ArgoCD, cluster do not start-up. This issue is not happening if strimzi-operator is deployed manually with helm chart.

PVC created for Zookeeper nodes keep are terminated by ArgoCD when doing the synchronization.

See related issues:
https://github.com/strimzi/strimzi-kafka-operator/issues/7093
https://github.com/argoproj/argo-cd/issues/10974

**Comment by swamx** [comment]
I fixed this in strimi Operator, values.yaml add following param: labelsExclusionPattern: argocd.argoproj.io/instance

**Comment by ricsanfre** [comment]
Adding deleteClaim=true to Kafka Cluster storage configuration
 
Fixed with https://github.com/ricsanfre/pi-cluster/commit/d4c5dd6ecf512377806633ec8ea6fe5bb8b8e06b
