### ISSUE TITLE
Community.Crypto collection not present in ansible-runner docker image

### ISSUE THREAD

**Issue by bpartin2009** [ricsanfre/pi-cluster#260]
When using self-signed certs and setting enable_letsencrypt to false, the external_services.yml line 65 pulls in generate_custom_ca.yml
The generate_custom_ca.yml uses openssl modules that are not found in the ansible-runner docker image running on the Ansible Control Node.

**Comment by ricsanfre** [comment]
Hi @bpartin2009, thanks for opening this issue.

You are right that module is missing in the ansible-runner docker image.
